"""Risk-based E2E test 2/3: ISO 15118-2 Plug & Charge certificate chain.

PnC is the densest signature-handling path in the codebase: the EVCC presents
a contract certificate chain (``PaymentDetailsReq.cert_chain``), then signs its
``AuthorizationReq`` with the contract certificate's private key; the SECC
walks the chain and verifies the signature before it will advance the session.
The signing/verification machinery spans three of the codec's roots — the full
``V2GMessage`` document, the ``AuthorizationReq`` fragment that carries the PnC
parameters, and the ``SignedInfo`` xmldsig fragment the signature is computed
over (ADR-0002 § fragment/xmldsig). A regression anywhere in that chain breaks
PnC silently in the smoke layer's eyes unless something asserts the signed
artifacts actually crossed the wire.

This test drives a full ISO 15118-2 PnC + TLS session over veth against the
realistic PKI material under ``app/shared/pki/iso15118_2/certs/`` (generated by
``create_certs.sh``) with the EXI capture tap on, then asserts:

* the session terminates cleanly — and because the SECC refuses to advance on a
  signature it cannot verify (``stop_state_machine`` on verification failure), a
  clean ``SessionStop`` is itself end-to-end proof that the signed messages
  validated;
* the contract certificate chain was actually presented on the wire
  (``PaymentDetailsReq`` carries a populated ``cert_chain``);
* the ``AuthorizationReq`` was genuinely signed (its header carries a
  ``Signature`` with both a ``SignedInfo`` and a ``SignatureValue``);
* the signed sub-element and xmldsig roots were exercised (an
  ``AuthorizationReq`` fragment and a ``SignedInfo`` xmldsig record appear in
  the capture).

When certificate material is absent the test skips with a clear reason rather
than failing, so a missing-cert environment yields a yellow skip instead of a
red gate.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app.shared.exi_codec import EXI
from app.shared.messages.enums import Namespace

from tests.conformance.e2e._capture_session import drive_session

PERSONALITIES_DIR = Path(__file__).resolve().parents[1] / "personalities"
ISO2_NS = Namespace.ISO_V2_MSG_DEF.value
XMLDSIG_NS = Namespace.XML_DSIG.value
PKI_CERTS_DIR = (
    Path(__file__).resolve().parents[3]
    / "app"
    / "shared"
    / "pki"
    / "iso15118_2"
    / "certs"
)


def _require_pki() -> None:
    contract_leaf = PKI_CERTS_DIR / "contractLeafCert.pem"
    if not contract_leaf.exists():
        pytest.skip(
            "ISO 15118-2 PnC certificate material is absent at "
            f"{PKI_CERTS_DIR} — generate with "
            "`bash app/shared/pki/create_certs.sh -v iso-2` to run this test"
        )


def test_iso2_pnc_certificate_chain(launch_emulator, exi_codec, tmp_path):
    _require_pki()

    capture_path = tmp_path / "iso2_pnc.jsonl"
    result = drive_session(
        launch_emulator,
        evcc_personality=PERSONALITIES_DIR / "iso2-evcc.yaml",
        secc_personality=PERSONALITIES_DIR / "iso2-secc.yaml",
        capture_path=capture_path,
        timeout_seconds=90,
    )

    # Clean termination under PnC+TLS == the SECC accepted every signature.
    assert result.completed, (
        "ISO-2 PnC session did not complete cleanly: "
        f"evcc_done={result.evcc_done}, secc_done={result.secc_done}"
    )

    # ---- The signed-message roots were exercised ----
    assert any(
        r.root == "fragment" and r.model == "AuthorizationReq" for r in result.records
    ), "no AuthorizationReq fragment (PnC params) captured — PnC path not exercised"
    assert any(
        r.root == "xmldsig" and r.model == "SignedInfo" for r in result.records
    ), "no SignedInfo xmldsig record captured — no signature was computed/verified"

    # ---- Contract certificate chain presented on the wire ----
    payment_details = _first_document(result, ISO2_NS, "PaymentDetailsReq")
    pd_msg = EXI().from_exi_document(payment_details.payload, ISO2_NS)
    payment_details_req = pd_msg.body.payment_details_req
    assert payment_details_req.cert_chain is not None, (
        "PaymentDetailsReq carried no contract certificate chain"
    )
    assert payment_details_req.cert_chain.certificate is not None, (
        "PaymentDetailsReq contract cert chain has no leaf certificate"
    )

    # ---- AuthorizationReq is genuinely signed, end to end ----
    authorization = _first_document(result, ISO2_NS, "AuthorizationReq")
    auth_msg = EXI().from_exi_document(authorization.payload, ISO2_NS)
    signature = auth_msg.header.signature
    assert signature is not None, "AuthorizationReq header carried no Signature"
    assert signature.signed_info is not None, (
        "AuthorizationReq Signature has no SignedInfo"
    )
    assert signature.signature_value is not None, (
        "AuthorizationReq Signature has no SignatureValue"
    )


def _first_document(result, namespace, model_name):
    """Return the first captured document record for ``model_name``.

    Encode-side records key by the concrete message name (decode-side ISO-2
    records key by ``V2G_Message``), so this finds the message as it was put
    on the wire by whichever peer authored it.
    """
    for rec in result.documents(namespace=namespace):
        if rec.model == model_name:
            return rec
    raise AssertionError(
        f"no {model_name} document captured in namespace {namespace}; "
        f"captured models: {sorted(result.model_names(root='document'))}"
    )
